### ISSUE TITLE
insertPos becomes undefined, NaN

### ISSUE THREAD

**Issue by micuat** [Jisuanke/CodeMirror-Record#20]
hi, first of all thank you for this amazing library!

I found a weird bug at https://github.com/Jisuanke/CodeMirror-Record/blob/master/src/CodePlay.js#L303
that fails with error that `insertPos` is `[undefined, NaN]`.

I extracted the records here
https://www.khm.de/~n.hieda/cm-undefined.txt

Also it's live on my app, on link "fdf play" after 2 minutes or so
https://gorgeous-pickle-kookaburra.glitch.me/

The error happens at t = 206414. Also by modifying the code to skip `undefined`s, I found that same error is happening at t = 206709 and 207004. But I don't see any problem in the records (I guess the raw record above will be parsed once it's loaded, and there something "wrong" happens) and there seems no conflicts by skipping `undefined` cases.

**Comment by haoranyu** [comment]
> The error happens at t = 206414. Also by modifying the code to skip `undefined`s, I found that same error is happening at t = 206709 and 207004. But I don't see any problem in the records (I guess the raw record above will be parsed once it's loaded, and there something "wrong" happens) and there seems no conflicts by skipping `undefined` cases.

I checked the records. Fortunately, the recorder seems to work fine. I will do more detailed checks on the player later. Thank you for pointing this out.

**Comment by haoranyu** [comment]
We studied this record. This seems to be an edge case. 

It combines three consecutive mouse movements in the same direction, but only one unique position is recorded. It causes the position of the three compressed records to be expanded to not be expanded into three positions. I haven't been able to find a way to recurrent this kind of problem in the recorder. 

If you find it, you are welcome to tell me or contribute through PR.

I will submit a PR first so that the Player can be compatible with the case here first.

**Comment by micuat** [comment]
wow I don't understand but thank you for taking time to figure out the problem. also kudos to @flordefuego for finding this bug.

**Comment by haoranyu** [comment]
> wow I don't understand but thank you for taking time to figure out the problem. also kudos to @flordefuego for finding this bug.

You may try the code on the following branch and see if the result is as expected?

https://github.com/Jisuanke/CodeMirror-Record/pull/22
